### ISSUE TITLE
[refactor] backend to typescript

### ISSUE THREAD

**Issue by yingliucreates** [LTL31223/online-store#5]
TypeScript for front-end works but back-end doesn't work.

Attempted dev script: 
"dev": "NODE_ENV=development nodemon --exec ts-node-dev server/server.ts & NODE_ENV=development webpack-dev-server"

error got:

[nodemon] 2.0.22
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: ts,json
[nodemon] starting `ts-node server/server.ts`
sh: ts-node: command not found
[nodemon] failed to start process, "ts-node" exec not found
[nodemon] Error
    at Bus.<anonymous> (/Users/yingliu/Desktop/online-store/node_modules/nodemon/lib/nodemon.js:158:25)
    at Bus.emit (node:events:525:35)
    at ChildProcess.<anonymous> (/Users/yingliu/Desktop/online-store/node_modules/nodemon/lib/monitor/run.js:195:11)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)

**Comment by htinlinnag1993** [comment]
Resolved here: https://github.com/LTL31223/online-store/pull/6#issue-1658272153

ts-node for running TypeScript code directly without having to wait for it be compiled

{
"watch": ["src"],
"ext": ".ts,.js",
"ignore": [],
"exec": "npx ts-node ./src/index.ts"
}

https://khalilstemmler.com/blogs/typescript/node-starter-project/
